### ISSUE TITLE
No such file or directory /dev/mei0

### ISSUE THREAD

**Issue by tele1** [intel/INTEL-SA-00075-Linux-Detection-And-Mitigation-Tools#1]
**_Edited._**
I found 1.2 https://downloadcenter.intel.com/download/26799/INTEL-SA-00075-Linux-Detection-and-Mitigation-Tools

and from *.doc

> Open Terminal and list available devices
> ls /dev/mei*
> If the result is a mei* device node will  0; then re-run the application with correct node
> e.g sudo ./ INTEL-SA-00075-Unprovisioning-Tool –d /dev/mei0

Please add this to README ,
and little documentation.
 thanks :-)

However for older hardware I hope: turn off any control from from outside in Bios 
and new kernel without remote vulnerable 
and firewall with closed  16992-16995 ports, 
reduces the problem.

**Comment by idesai** [comment]
@tele1  thanks.
