### ISSUE TITLE
Error: No such file or directory /dev/mei0

### ISSUE THREAD

**Issue by thinrope** [intel/INTEL-SA-00075-Linux-Detection-And-Mitigation-Tools#5]
I was running this tool on various (old) systems, but on some got this error upon execution of `INTEL-SA-00075-Discovery-Tool`:
````
Error: No such file or directory /dev/mei0
Cannot establish a handle to the Intel(R) MEI driver. Refer to Tool User Guide for more information.
````
Looking around I realised that there is no support in their kernel for MEI, i.e. no driver is loaded. It took me a few moments, but I am sure some people will get stuck for good.

Please add either in the documentation and/or in the MSGs in the code around [line 447](https://github.com/intel/INTEL-SA-00075-Linux-Detection-And-Mitigation-Tools/blob/master/INTEL-SA-00075-Discovery-Tool.c#L447) that:
* this tool requires MEI support from the running kernel (in recent kernels that is `CONFIG_INTEL_MEI` and `CONFIG_INTEL_MEI_ME` under `Device Drivers|Misc devices`)
* WARNING: Being unable to access /dev/mei0 does NOT imply that this system has no MEI support and may be still vulnerable.

(yes, that may raise extra questions like "How do I compile my kernel", but at least people will have some direction what to look for)

**Comment by idesai** [comment]
Thanks. Added to the readme.
